# Generated by Django 3.1.5 on 2021-02-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimmer',
            name='swimmer_id',
            field=models.IntegerField(default=488426),
        ),
    ]
