# Generated by Django 3.1.5 on 2021-02-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_swimmer_swimmer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimmer',
            name='swimmer_id',
            field=models.CharField(default='488426', max_length=7),
        ),
    ]
