# Generated by Django 3.1.5 on 2021-02-05 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210204_2149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
